---
- hosts: localhost
  tasks:
    - name: installing java
      shell: sudo yum install java-1.8* -y

    - name: installing wget
      shell: sudo yum -y install wget

    - name: installing linux
      shell: sudo amazon-linux-extras install epel -y

    - name: installing wget
      shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: installing rpm
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: installing jenkins
      shell: sudo yum install jenkins -y

    - name: start jenkins
      shell: sudo systemctl start jenkins && sudo systemctl enable jenkins
